# Site settings
title: "On Software Engineering, Mathematics<br>and Philosophy"
author: "PKJ"
description: "This is a blog about software, some mathematics, and the occasional philosophy. Not necessarily in that order."
keywords: "Software Engineering, Mathematics, Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: "I am a engineer trying to explore and learn new fields. In my leisure I like to read some philosophy as well."
colophon: "© Team Xvenom"

baseurl: "/coding_tales"
url: "https://xvepkj.github.io"

twitter_username: 
github_username: xvepkj 
linkedin_username:
facebook_username: 
google-analytics:

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
