# Site settings
title: "On Software Engineering, Mathematics<br>and Philosophy"
author: "Pratham Kumar Jha"
description: "This is a blog about software, some mathematics, and the occasional philosophy. Not necessarily in that order."
keywords: "Software Engineering, Mathematics, Philosophy, Scala, Epistemology, Existentialism, Programming, Machine-Learning, Artificial Intelligence, Statistics, Probability, Puzzles"
biography: "I am software engineer trying to be an engineer"
colophon: "© Team Xvenom"

baseurl: ""
url: ""

twitter_username: 
github_username: 
linkedin_username:
facebook_username: 
google-analytics:

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
