source "https://rubygems.org/"

gem "jekyll"
gem "webrick"
gem "kramdown-math-katex"
gem "rake"

# gem "github-pages", group: :jekyll_plugins
# # If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-remote-theme"
  gem "jekyll-seo-tag"
end